version: "2"

networks:
  mongodb:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.169.0.0/24

services:
  provisioner.mongodb:
    container_name: provisioner.mongodb
    build: ./provisioner
    command: -d /usr/src/app config,1.config.mongodb:27017 replica1,1.replica1.mongodb:27017 router,mongodb
    volumes:
      - ./provisioner:/usr/src/app
      - ./data/keys:/usr/src/keys
    networks:
      - mongodb

  mongodb:
    container_name: mongodb
    hostname: mongodb
    image: mongo:3.6
    command: mongos -f /data/etc/mongo.conf
    working_dir: /usr/src
    volumes:
      - ./data/router/etc:/data/etc
      - ./data/keys:/data/keys
    ports:
      - 27017:27017
    depends_on:
      - 1.config.mongodb
      - 2.config.mongodb
      - 3.config.mongodb
      - 1.replica1.mongodb
      - 2.replica1.mongodb
      - 3.replica1.mongodb
    networks:
      - mongodb

  1.config.mongodb:
    container_name: 1.config.mongodb
    hostname: 1.config.mongodb
    image: mongo:3.6
    command: mongod -f /data/etc/mongo.conf
    working_dir: /usr/src
    volumes:
      - ./data/config/1:/data/db
      - ./data/config/etc:/data/etc
      - ./data/keys:/data/keys
    networks:
      - mongodb

  2.config.mongodb:
    container_name: 2.config.mongodb
    hostname: 2.config.mongodb
    image: mongo:3.6
    command: mongod -f /data/etc/mongo.conf
    working_dir: /usr/src
    volumes:
      - ./data/config/2:/data/db
      - ./data/config/etc:/data/etc
      - ./data/keys:/data/keys
    networks:
      - mongodb

  3.config.mongodb:
    container_name: 3.config.mongodb
    hostname: 3.config.mongodb
    image: mongo:3.6
    command: mongod -f /data/etc/mongo.conf
    working_dir: /usr/src
    volumes:
      - ./data/config/3:/data/db
      - ./data/config/etc:/data/etc
      - ./data/keys:/data/keys
    networks:
      - mongodb

  1.replica1.mongodb:
    container_name: 1.replica1.mongodb
    hostname: 1.replica1.mongodb
    image: mongo:3.6
    command: mongod -f /data/etc/mongo.conf
    working_dir: /usr/src
    volumes:
      - ./data/replica1/1:/data/db
      - ./data/replica1/etc:/data/etc
      - ./data/keys:/data/keys
    networks:
      - mongodb

  2.replica1.mongodb:
    container_name: 2.replica1.mongodb
    hostname: 2.replica1.mongodb
    image: mongo:3.6
    command: mongod -f /data/etc/mongo.conf
    working_dir: /usr/src
    volumes:
      - ./data/replica1/2:/data/db
      - ./data/replica1/etc:/data/etc
      - ./data/keys:/data/keys
    networks:
      - mongodb

  3.replica1.mongodb:
    container_name: 3.replica1.mongodb
    hostname: 3.replica1.mongodb
    image: mongo:3.6
    command: mongod -f /data/etc/mongo.conf
    working_dir: /usr/src
    volumes:
      - ./data/replica1/3:/data/db
      - ./data/replica1/etc:/data/etc
      - ./data/keys:/data/keys
    networks:
      - mongodb
